spring.application.name=distribution-sales-techfira


#spring.datasource.url = jdbc:mysql://avnadmin:AVNS_jIE08NfrWwdKj4NIWNm@mysql-2646da60-awaisbrohi000-4804.e.aivencloud.com:26188/defaultdb?ssl-mode=REQUIRED
#spring.datasource.username = avnadmin
#spring.datasource.password = AVNS_jIE08NfrWwdKj4NIWNm

 spring.datasource.url = jdbc:mysql://localhost:3306/techfiradb?createDatabaseIfNotExist=true
   spring.datasource.username = root
   spring.datasource.password = root
 debug=true
#spring.datasource.url = jdbc:mysql://localhost:3333/sales_treasure?createDatabaseIfNotExist=true
#spring.datasource.username = root
#spring.datasource.password = Pirates@29
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=kkfarazahmed@gmail.com
spring.mail.password=axsz ppsp kaqz xkgz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#spring.datasource.url = jdbc:mysql://localhost:3306/techfiradb?createDatabaseIfNotExist=true
#spring.datasource.username = root
#spring.datasource.password = gmbaloch123$

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql = true
spring.jpa.hibernate.ddl-auto = update